apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-third
spec:
  selector:
    matchLabels:
      app: service-third
  replicas: 4
  template:
    metadata:
      labels:
        app: service-third
    spec:
      containers:
        - name: service-third
          image: service-third:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: service-third
spec:
  selector:
    app: service-third
  ports:
    - protocol: TCP
      port: 8080
  type: NodePort